### ISSUE TITLE
Bug error: when using a number as (sub)location name

### ISSUE THREAD

**Issue by Florisklooster** [ArtesiaWater/field_form#11]
When the location name is a number, or the sublocation-name is a number when sublocations are used (in this case the location name can be a number), the json is loaded and shown in the app, but added measurements can not be uploaded to the ftp server (a loading display is shown which does not go away unless the app is restarted).

I would like the option of having a number as (sub)location name. But if this is not (yet) possible I think it should be something that is mentioned in the README file.

By the way if a letter is added to the number (e.g. not '342' but '342z' or '34_2') the app works just fine.

**Comment by rubencalje** [comment]
It is important that location-ids and sublocation-ids are unique, as they are used as a unique identifier of the location in the measurement-files. As you suggested, I added some info in the README file.

Numbers are not allowed as the location- or sublocation-id. But, as you mention, FieldForm does not check if this is the case (yet). Using numbers or non-unique location-ids can cause problems, even needing a reinstallation of the app if things go sour. I will add some checks in the future, to catch these user-errors before they cause problems.

Thanks for adding the issue.
