### ISSUE TITLE
Group inputfields are not working when using sublocations

### ISSUE THREAD

**Issue by Florisklooster** [ArtesiaWater/field_form#15]
It is possible to define inputfields (as a list) for groups. As described in the readme, this is a list of inputfield-ids to be measured at the locations of the group (trumped by the inputfields of each location). However, right now if there are no inputfields defined for the sublocation it simply gives all inputfield-ids defined instead of just the inputfield-ids that should be measured for the specific group.  
This does work properly if no sublocations are provided, that is probaly also the reason that for colors the app is functioning as expected.

By the way, the app and the latest update are really appreciated!

**Comment by rubencalje** [comment]
When sublocations are used, the group needs to be defined for each sublocation, if you want to use the inputfields from the group. The inputfields of the group of the (parent) location are ignored.
