### ISSUE TITLE
Entered value(s) disappear after scrolling

### ISSUE THREAD

**Issue by Florisklooster** [ArtesiaWater/field_form#21]
Entered value(s) that were previously filled in disappear after the particular inputfield moves out of the screen, when scrolling down the inputfields. It happens (at least) with the values in the 'number' and 'text' inputfields. The data itself is not really gone because, once clicked on the 'Gereed'/'Ready' button, the data entered in the concerning (empty) field(s), is saved to the measurements*.csv. 

It depends a bit on how you scroll and how far, but the issue happens quite consistently.

**Comment by rubencalje** [comment]
Thanks for the report. On which platform were these issues: Android and/or iOS?

**Comment by Florisklooster** [comment]
On both platforms
