### ISSUE TITLE
Example location file is incorrect

### ISSUE THREAD

**Issue by CastilioJC** [ArtesiaWater/field_form#4]
- When using the example json location file you get an error. The comma on line 4 has to be removed.
- By inputfield is "values" defined but under locations the field "head" is used, so the field is not visible in the app.
- By "location_2" there is no inputfield defined. In the app it shows by this location all the inputfields is that correct?

**Comment by rubencalje** [comment]
Thanks for reporting this. I edited the example. I also added a settings-section, a second group, and a photo-inputfield. When no inputfields are defined for a location, the app shows all inputfields, that is correct.
