### ISSUE TITLE
In iOS werkt toevoegen  opties bij keuzeveld niet

### ISSUE THREAD

**Issue by CastilioJC** [ArtesiaWater/field_form#6]
ALs je in de iOS via "instellingen"  - > "Pas invoervelden aan"  en dan bij een invoerveld van het type "choice" een extra optie toevoegt (via +) en vervolgens op "gereed" klikt wordt de nieuwe optie niet toegevoegd/opgeslagen

**Comment by rubencalje** [comment]
Hi @CastilioJC, thanks for reporting the issue. It is present in the Android-version as well. An english reference: When adding or changing an input field it is impossible to add extra options for the type 'choice'.

I will fix the issue somewhere this month.

**Comment by rubencalje** [comment]
The issue was caused by a minor bug in the code. It is now fixed, but I do not have access to an Apple computer right now. I will upload a new version to the app stores next week.

**Comment by rubencalje** [comment]
This is fixed since version 1.0.7
